// Package colortest contains useful functions and logic for testing with the color package.
package colortest

import (
	"fmt"
	"strings"
	"testing"

	"github.com/leep-frog/command"
	"github.com/leep-frog/command/color"
)

// StubTput will write to stdout for each format.Apply call rather than
// actually running tput. See the `colortest.FakeOutput` function for
func StubTput(t *testing.T) {
	command.StubValue(t, &color.TputCommand, func(output command.Output, args ...interface{}) error {
		var ss []string
		for _, a := range args {
			ss = append(ss, fmt.Sprintf("%v", a))
		}
		output.Stdoutf("__tput_%s__", strings.Join(ss, "_"))
		return nil
	})
}

// FakeOutput returns the fake tput output generated by StubTput.
func FakeOutput(f *color.Format) string {
	ss := []string(*f)
	return fmt.Sprintf("__tput_%s__", strings.Join(ss, "_"))
}

// WrapOutput wraps the provided string with the prefix format and init format.
func WrapOutput(f *color.Format, s string) string {
	return fmt.Sprintf("%s%s%s", FakeOutput(f), s, FakeOutput(color.Init()))
}
