echo ============ Generating files...
k="$(go run simple_sourcer.go)"
cat $k
echo ========== Sourcing file...
source $k
echo ========== Running todo...
_custom_execute todo
echo ========== Done
